/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ahms.ui;

import com.ahms.boundary.security.PaymentTypesBoundary;
import com.ahms.model.entity.PaymentTypes;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author jorge
 */
public class PaymentModule extends javax.swing.JDialog {

    private BigDecimal importeTotal = BigDecimal.ZERO;
    private BigDecimal importePagado = BigDecimal.ZERO;
    private BigDecimal importeSobrante = BigDecimal.ZERO;
    private BigDecimal importeRestante = BigDecimal.ZERO;
    private PaymentTypesBoundary paymentTypesBoundary;
    private CheckOutForm parentDialog;
    
    public PaymentModule(CheckOutForm parent, boolean modal, BigDecimal total) {
        super(parent, modal);
        initComponents();
        parentDialog = parent;
        paymentTypesBoundary = new PaymentTypesBoundary();
        
        jlCambio.setVisible(false);
        jlMontoCambio.setVisible(false);
        cargarTiposPago();
        
        importeTotal = total.setScale(2,RoundingMode.HALF_EVEN);
        jlTotal.setText("$ "+ importeTotal.toString());
    }
    
    private void cargarTiposPago() {
        jcbTipoPago.removeAllItems();
        List<PaymentTypes> payments = paymentTypesBoundary.searchAll(new PaymentTypes());
        for(PaymentTypes payment : payments){
            jcbTipoPago.addItem(payment);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbTipoPago = new javax.swing.JComboBox();
        jtImporteRecibido = new javax.swing.JTextField();
        jbPago = new javax.swing.JButton();
        jlCambio = new javax.swing.JLabel();
        jlMontoCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlTotal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jlTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTotal.setText("total cuenta");

        jLabel1.setText("Tipo pago:");

        jLabel2.setText("Importe recibido:");

        jcbTipoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ahms/ui/resources/pack2/money_dollar.png"))); // NOI18N
        jbPago.setText("Procesar pago");
        jbPago.setToolTipText("");
        jbPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPagoActionPerformed(evt);
            }
        });

        jlCambio.setText("Cambio:");

        jlMontoCambio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jlMontoCambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlMontoCambio.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtImporteRecibido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTipoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlCambio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlMontoCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPago)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtImporteRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPago)
                    .addComponent(jlMontoCambio)
                    .addComponent(jlCambio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPagoActionPerformed
        PaymentTypes selectedPayment = (PaymentTypes) jcbTipoPago.getSelectedItem();
        importePagado = new BigDecimal(jtImporteRecibido.getText()).setScale(2, RoundingMode.UP);
        //validaciones
        switch(selectedPayment.getPayId()){
            case 1: 
                if(importePagado.compareTo(importeTotal) > 0) // importe pagado > importe total, hay que dar feria
                {
                    importeSobrante = importePagado.subtract(importeTotal).setScale(2,RoundingMode.HALF_EVEN);
                    jlCambio.setText("Cambio:");
                    jlCambio.setVisible(true);
                    jlMontoCambio.setText(importeSobrante.toString());
                    jlMontoCambio.setVisible(true);
                    
                    //TRANSACCIONES CORRESPONDIENTES
                    
                    //----------------------------------
                } else { //si el importe pagado es menor o igual al importe total actualizar montos en checkout
                    //TRANSACCIONES CORRESPONDIENTES ---
                    
                    //----------------------------------
                    importeRestante = importeTotal.subtract(importePagado).setScale(2,RoundingMode.UP);
                    jlCambio.setText("Restante:");
                    jlCambio.setVisible(true);
                    jlMontoCambio.setText(importeRestante.toString());
                    jlMontoCambio.setVisible(true);
                    
                    //actualizar montos en el checkout
                    parentDialog.totalPagado = parentDialog.totalPagado.add(importePagado);
                    parentDialog.totalPending = parentDialog.totalOriginal.subtract(parentDialog.totalPagado).setScale(2, RoundingMode.UP);
                    parentDialog.regenerateTotals();
                    this.dispose();
                }
            break;
            case 2: case 3: 
            break;
        }
    }//GEN-LAST:event_jbPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaymentModule dialog = new PaymentModule(new CheckOutForm(null, true, null), true, new BigDecimal(4500));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbPago;
    private javax.swing.JComboBox jcbTipoPago;
    private javax.swing.JLabel jlCambio;
    private javax.swing.JLabel jlMontoCambio;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTextField jtImporteRecibido;
    // End of variables declaration//GEN-END:variables
}
